package irstats_test

import (
	"fmt"
	"net/http"
	"testing"

	"github.com/skippyza/irstats"
	"github.com/stretchr/testify/assert"
)

func TestSubSessionData(t *testing.T) {
	mux, server, client := setup(t)
	defer teardown(server)

	path := "/membersite/member/GetSubsessionResults"
	mux.HandleFunc(path, func(w http.ResponseWriter, r *http.Request) {
		testMethod(t, r, "POST")
		w.WriteHeader(http.StatusOK)
		fmt.Fprint(w, loadFixture("testdata/subsession_data.json"))
	})

	result, err := client.SubSessionData(irstats.String("1000"), irstats.String("2000"))
	assert.NoError(t, err)

	expected := &irstats.SubSessionResult{
		CategoryID:            2,
		CautionType:           2,
		CornersPerLap:         13,
		DriverChangeParam1:    -1,
		DriverChangeParam2:    -1,
		DriverChangeRule:      0,
		DriverChanges:         0,
		EventAverageLap:       911360,
		EventLapsComplete:     14,
		EventStrengthOfField:  3443,
		EventType:             5,
		LeagueSeasonID:        "",
		LeagueID:              "",
		LeaveMarbles:          0,
		MaxTeamDrivers:        1,
		MaxWeeks:              12,
		MinTeamDrivers:        1,
		NcautionLaps:          0,
		Ncautions:             0,
		NLapsForQualAVG:       2,
		NLapsForSoloAVG:       5,
		NLeadChanges:          0,
		PointsType:            "race",
		PrivateSessionID:      -1,
		RaceWeekNum:           7,
		RservStatus:           "",
		RubberLevelPractice:   -1,
		RubberLevelQualify:    -1,
		RubberLevelRace:       -1,
		RubberLevelWarmup:     -1,
		SeasonName:            "Apex+Racing+Academy+F3+Championship+-+2021+Season+2",
		SeasonQuarter:         2,
		SeasonShortname:       "2021+Season+2",
		SeasonYear:            2021,
		SeasonID:              3153,
		SeriesName:            "Apex+Racing+Academy+F3+Championship",
		SeriesShortname:       "Apex+Racing+Academy+F3+Championship",
		SeriesID:              431,
		SessionID:             123456789,
		SessionName:           "",
		SimSessionType:        3,
		SimulatedStartTime:    "2021-05-08+17%3A35",
		SpecialEventType:      -1,
		SpecialEventTypeText:  "",
		StartTime:             "2021-05-08+17%3A15%3A00",
		SubsessionID:          10000000,
		TimeOfDay:             2,
		TrackConfigName:       "N%2FA",
		TrackName:             "Circuit+Gilles+Villeneuve",
		TrackID:               218,
		WeatherFogDensity:     0,
		WeatherRh:             61,
		WeatherSkies:          1,
		WeatherTempUnits:      0,
		WeatherTempValue:      78.791275,
		WeatherType:           1,
		WeatherVarInitial:     0,
		WeatherVarOngoing:     0,
		WeatherWindDir:        6,
		WeatherWindSpeedUnits: 0,
		WeatherWindSpeedValue: 12.379519,

		Drivers: []irstats.SubSessionDriver{
			{
				AggChampPoints:       64,
				AvgLap:               0,
				BestLapNum:           -1,
				BestLapTime:          -1,
				BestNLapsNum:         -1,
				BestNLapsTime:        -1,
				BestQualLapAt:        0,
				BestQualLapNum:       -1,
				BestQualLapTime:      -1,
				CarColor1:            "FFE200",
				CarColor2:            "125B30",
				CarColor3:            "132347",
				CarNumberColor1:      "FFFFFF",
				CarNumberColor2:      "777777",
				CarNumberColor3:      "000000",
				CarPattern:           1,
				CarClassID:           870,
				CarID:                106,
				CarNum:               "26",
				CarNumberFont:        0,
				CarNumberSlant:       0,
				CarSponsor1:          0,
				CarSponsor2:          0,
				CCName:               "Dallara+F3",
				CCNameShort:          "Dallara+F3",
				ChampPoints:          0,
				ClassInterval:        -1,
				ClubID:               1,
				ClubName:             "International+Club",
				ClubPoints:           0,
				ClubShortName:        "International",
				CustomerID:           100000,
				DamageModel:          0,
				DisplayName:          "Steven+Inskip",
				Division:             1,
				DivisionName:         "Gold+Division",
				DropRacePoints:       0,
				EvtTypeName:          "Race",
				FinishPos:            25,
				FinishPosInClass:     25,
				GripCompoundPractice: -1,
				GripCompoundQualify:  -1,
				GripCompoundRace:     -1,
				GripCompoundWarmup:   -1,
				GroupID:              188953,
				HeatInfoID:           -1,
				HelmColor1:           "ffe200",
				HelmColor2:           "125b30",
				HelmColor3:           "132347",
				HelmPattern:          64,
				HostID:               "",
				Incidents:            2,
				Interval:             -1,
				LapsComplete:         0,
				LapsLead:             0,
				LeaguePoints:         "",
				LeagueAggPoints:      "",
				LicenseChangeOval:    -1,
				LicenseChangeRoad:    -1,
				LicenseCategory:      "Road",
				LicenseGroup:         3,
				MaxPctFuelFill:       -1,
				Multiplier:           1,
				NewCPI:               35.6994667,
				NewIrating:           2683,
				NewLicenseLevel:      14,
				NewSubLevel:          267,
				NewTTRating:          1401,
				OfficialSession:      1,
				OldCPI:               36.0043106,
				OldIrating:           2697,
				OldLicenseLevel:      14,
				OldSubLevel:          269,
				OldTTRating:          1401,
				OptLapsComplete:      0,
				Pos:                  25,
				QualLapTime:          -1,
				ReasonOut:            "Running",
				ReasonOutID:          0,
				RestrictResults:      "",
				SessionStartTime:     1620494100000,
				SimSesName:           "PRACTICE",
				SimSesNum:            -2,
				SimSesTypeName:       "Open+Practice",
				StartPos:             -1,
				SubsessionFinishedAt: 1620496278000,
				SuitColor1:           "08fff8",
				SuitColor2:           "8683ff",
				SuitColor3:           "00ff12",
				SuitPattern:          23,
				TrackCategory:        "Road",
				TrackCatID:           2,
				VehicleKeyID:         12003,
				WeightPenaltyKG:      -1,
				WheelChrome:          -1,
				WheelColor:           "N%2FA",
			},
		},
	}
	assert.Equal(t, expected, result)
}
